// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cehyvmdrnzidrmlvwzqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlaHl2bWRybnppZHJtbHZ3enF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNTE5MjUsImV4cCI6MjA2MjgyNzkyNX0.AYf-BtH4IKECmUdBl8HCbhZOIB5zRxdGzLbmnLhSQmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);